from setuptools import setup, find_packages
import os

setup(
    name='openlegis.sagl',
    version='5.1',
    description="Plataforma de Processos Digitais",
    long_description=open("README.txt").read() + "\n" +
                     open(os.path.join("docs", "HISTORY.txt")).read(),
    classifiers=[
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
    keywords='Zope',
    author='OpenLegis',
    author_email='contato@openlegis.com.br',
    url='https://github.com/openlegis-br/sagl/',
    license='GPL',
    include_package_data=True,
    zip_safe=False,
    python_requires='>=3.8',
    install_requires=[
        'setuptools',
        'Pillow',
        'Products.CMFCore',
        'Products.CMFDefault',
        'Products.CMFFormController',
        'Products.CMFUid',
        'Products.DCWorkflow',
        'Products.ExternalEditor',
        'Products.GenericSetup',
        'Products.ZMySQLDA',
        'Products.AdvancedQuery',
        'Products.ExtendedPathIndex',
        'z3c.autoinclude',
        'pyoai',
        'appy',
        'zope.globalrequest',
        'five.grok',
        'five.formlib',
        'five.localsitemanager',
        'grokcore.annotation',
        'grokcore.component',
        'grokcore.formlib',
        'grokcore.layout',
        'grokcore.security',
        'grokcore.site',
        'grokcore.view',
        'grokcore.viewlet',
        'martian',
        'reportlab',
        'trml2pdf',
    ],
    entry_points={},
    packages=find_packages(include=['openlegis', 'openlegis.*']), # Find packages under 'openlegis'
)
